language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+

before_install:
 - chmod +x gradlew
