language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+

before_install:
 - yes | sdkmanager "platforms;android-27"
 - chmod +x gradlew
